# Generated by Django 5.2.5 on 2025-08-30 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collect", "0002_payment"),
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="payment_date",
        ),
        migrations.AlterField(
            model_name="payment",
            name="collect",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_payments",
                to="collect.collect",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_payments_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
